import time
from time import sleep

RED = "RED"
GREEN = "GREEN"
BLUE = "BLUE"

TIME_THRESHOLD = 2.5 # seconds

# Vision sensor colorimetry parameters.
# TODO preliminary values taken from colorimetry analysis
HUE = {}
SATURATION = {}

HUE[RED]        = (0.90, 1.00)  # min and max hue for red
HUE[GREEN]      = (0.38, 0.55)
HUE[BLUE]       = (0.58, 0.63)

SATURATION[RED]        = (0.52, 0.82)  # min and max saturation for red
SATURATION[GREEN]      = (0.25, 0.57)
SATURATION[BLUE]       = (0.56, 0.76)

sign = lambda x: x and (1, -1)[x<0]


class SensorEventFilter():
    '''
    This class is used to filter out multiple detections of the same color
    by the vision sensor in a SmartTrain.

    It works by ignoring all detections of the given color that take place
    within a pre-defined time interval. The first event will be passed back
    to the caller, an instance of SmartTrain, via its process_event method.
    '''

    events = {}

    def __init__(self, train):
        '''
        
        :param train: an instance of SmartTrain
        '''
        self.train = train

    def filter_event(self, event_key):
        # events are discriminated by their color. If an event of a given
        # color is already stored here, it means that this current event is
        # possibly a double detection. Verify by checking event times.
        event_time = time.time()
        if event_key in self.events:
            if (event_time - self.events[event_key]) > TIME_THRESHOLD:
                # not a double detection. Alert caller and
                # redefine stored event
                self.events[event_key] = event_time
                self.train.event_processor.process_event(event_key)

            else:
                # double detection. Do nothing.
                pass

        # if event of current color is not stored here, store current event
        else:
            self.events[event_key] = event_time
            self.train.event_processor.process_event(event_key)


class EventProcessor:
    '''
    Delegate class that handles everything associated with sensor
    events in a SmartTrain instance.
    '''
    def __init__(self, train):
        '''

        :param train: an instance of SmartTrain
        '''
        self.train = train

    def process_event(self, event):
        '''
        Processes events pre-filtered by SensorEventFilter
        '''
        # red signal means stop at station

        print("Event:  ", event)

        if event in [RED]:

            self.train.check_acceleration_thread()

            # action = track.segments[event]

            sleep(0.01)
            self.train.stop()

            # after stopping at station, execute a Timer delay followed by a re-start
            self.train.timed_stop_at_station()

            # if a secondary train instance is registered, call its stop
            # method. But *do not* call its timed delay routine, since this
            # functionality must be commanded by the current train only.
            if self.train.secondary_train is not None:
                self.train.secondary_train.stop()

        # light blue signal causes power to be dropped to level 1
        elif event in [BLUE]:
            # the train might be moving backwards, so first we generate
            # a positive representation of the current power index (the
            # `accelerate` method will handle the actual sense of movement
            # for the new speed values).
            current_power_index_value = self.train.power_index * sign(self.train.power_index)

            # generate downward sequence of power index values. In this case,
            # we want to go way down to speed 1, thus we use zero for the new
            # index (it's being generated by a `range` call)
            new_power_index_value = 0
            power_index_step = -1
            power_index_range = list(range(current_power_index_value,
                                     new_power_index_value,
                                     power_index_step))

            # a sequence of 6 deceleration steps has 5 sleeping intervals. It
            # is executed in approx. 1 sec. Normalize so it takes about the
            # same time regardless of current speed.
            # sleep_time = 6. / len(power_index_range) * 0.2
            sleep_time = 6. / len(power_index_range) * 0.1 #TODO test for fast stop (2-car = 0.1, 1-car = 0.05)
            sleep_time *= 6. / current_power_index_value
            sleep_time *= 1.1 # fudge factor

            self.train.accelerate(power_index_range, sign(self.train.power_index), sleep_time=sleep_time)
